services:
  server:
    build:
      context: .
      target: final
    ports:
      - 5555:8080
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TodoDb;User Id=sa;Password=Password123.;Encrypt=false;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password123."
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P $${SA_PASSWORD} -Q 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlserver-data:
